config/routes.rb
Rails.application.routes.draw do
  # get 'users/index'
  # get 'users/show'
  root to: 'home#index'
  get "/home/about"

  # devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_for :users
  resources :users, :only => [:index, :show, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}

  attachment :profile_image

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :check_current_user_book?, only: [:edit]

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @user = current_user
  end

  def new
  	@book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def create
  	book = Book.new(book_params)
    # Association
    book.user_id = current_user.id
    @user = current_user
  	if book.save
      redirect_to book_path(book.id), notice: "You have creatad book successfully."
    else
      @books = Book.all
      @book = book
      render "index"
    end
  end

  def update
    book = Book.find(params[:id])
    if book.update(book_params)
      redirect_to book_path, notice: "Book was successfully update."
    else
      @book = book
      render "edit"
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path, notice: "Book was successfully deleted."
  end

  private
  def book_params
  	params.require(:book).permit(:title, :body)
  end

  def check_current_user_book?
    book = Book.find(params[:id])
    if current_user.id != book.user_id
      redirect_to books_path
    end

    # unless current_user.id == book.user_id
    #   redirect_to books_path
    # end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_sidebar.html.erb
<div class="col-xs-3">

  <!-- User info -->
	<h2>User info</h2>

  <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpg', fallback:"no_image.png", size:'100x100' %>

  <table class="table">
  	<tbody>
	    <tr>
		    <th>Name</th>
        <th><%= @user.name %></th>
	    </tr>
	    <tr>
		    <th>introduction</th>
        <th><%= @user.introduction %></th>
	    </tr>
  	</tbody>
  </table>

  <%= link_to "", edit_user_path(current_user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>

  <!-- New book -->
  <h2>New book</h2>
  <%= form_for(@book) do |f| %>
    <div class="field row">
      <label for="book_title">Title</label>
      <input class="col-xs-12 book_title" type="text" name="book[title]" id="book_title">
    </div>

    <div class="field row">
      <label for="book_opinion">Opinion</label>
      <textarea class="col-xs-12 book_body" name="book[body]" id="book_body"></textarea>
    </div>

    <div class="actions row" style="margin-top: 10px;">
      <input type="submit" name="commit" value="Create Book" class="btn btn-primary col-xs-12" data-disable-with="Create Book">
    </div>
  <% end %>
</div>

app/views/books/edit.html.erb
<div class="container">

  <% if @book.errors.any? %>
    <div style="color: red;">
      <ul>
        <h3><%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:</h3>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
      </ul>
    </div>
  <% end %>

	<div class="row">
		<h1>Editing Book</h1>
		    <%= form_for(@book) do |f| %>
	        <h4>Title</h4>
	        <%= f.text_field :title %>

	        <h4>Opinion</h4>
	        <%= f.text_area :body %>

          <%= f.submit "Update Book" %>
          <% end %>
          <h4><%= link_to "Show", book_path %> | <%= link_to "Back", books_path %></h4>
	</div>
</div>

app/views/books/index.html.erb
<div class="container">

  <div class="text-danger">
    <% if @book.errors.any? %>
        <ul>
          <h3><%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:</h3>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
        </ul>
    <% end %>
  </div>

	<div class="row">
		<%= render "books/sidebar" %>
		<div class="col-xs-9">

			<h2>Books</h2>

			<table class="table table-hover table-inverse">
        <thead>
          <tr>
          	<th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>

        <tbody>
        	<% @books.each do |book| %>
        		<tr>
            	<td>
            		<%= link_to user_path(book.user_id) do %>
            			<%= image_tag attachment_url(book.user, :profile_image, :fill, 50, 50, format: "jpg", fallback: "no_image.png"), size:'50x50'%>
            		<% end %>
            	</td>
			        <td><%= link_to book.title, book_path(book.id) %></td>
			        <td><%= book.body %></td>
        		</tr>
          <% end %>
        </tbody>
      </table>

		</div>
	</div>
</div>

app/views/books/new.html.erb
<%= render "books/sidebar" %>

app/views/books/show.html.erb
<div class="container">
	<div class="row">
		<%= render "books/sidebar" %>
		<div class="col-xs-9">

			<h1>Book detail</h1>
			<table class="table">
				<tbody>
					<tr>
						<!-- profile image -->
						<td>
							<%= link_to user_path(@book.user_id) do %>
			    			<%= image_tag attachment_url(@book.user, :profile_image, :fill, 50, 50, format: "jpg", fallback: "no_image.png"), size:'50x50'%><br>
			    			<%= @book.user.name %>
	    				<% end %>
    				</td>
    				<!-- title -->
						<td><%= link_to @book.title, user_path(@book.user) %></td>
						<!-- opinion -->
						<td><%= @book.body %></td>
						<!-- edditing button -->
						<% if current_user.id == @book.user_id %>
							<td><%= link_to "Edit", edit_book_path(@book.id), class: "btn-sm btn-success" %></td>
					 		<td><%= link_to "Destroy", book_path, class: "btn-sm btn-danger", method: :delete, data: {confirm: "本当に消しますか？"} %></td>
				 		<% end %>
				  </tr>
		    </tbody>
			</table>

		</div>
  </div>
</div>