config/routes.rb
Rails.application.routes.draw do
  # get 'users/index'
  # get 'users/show'
  root to: 'home#index'
  get "/home/about"

  # devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_for :users
  resources :users, :only => [:index, :show, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<!-- header -->
<header class="navbar navbar-fixed-top navbar-inverse" style="color: white;">
<div class="container" style="padding: 0, 20;">
  <nav class="nav navbar-nav navbar-left"><h4>Bookers</h4></nav>
  <nav class="nav navbar-nav navbar-right">
    <ul class="nav navbar-nav mr-auto">
      <% if user_signed_in? %>
        <!-- ログインしている場合 -->
        <li>
          <!-- <a class="glyphicon glyphicon-home" href="/users/id"> Home</a> -->
          <%= link_to " Home", user_path(current_user.id), class: "glyphicon glyphicon-home" %>
        </li>
        <li>
          <!-- <a class="glyphicon glyphicon-user" href="/users/index"> Users</a> -->
          <%= link_to " Users", users_path, class: "glyphicon glyphicon-user" %>
        </li>
        <li>
          <!-- <a class="glyphicon glyphicon-book" href="/books"> Books</a> -->
          <%= link_to " Books", books_path, class: "glyphicon glyphicon-book" %>
        </li>
        <li>
          <!-- <a class="glyphicon glyphicon-log-out" rel="nofollow" data-method="delete" href="/users/sign_out"> logout</a> -->
          <%= link_to " logout", destroy_user_session_path, class: "glyphicon glyphicon-log-out", method: :delete %>
        </li>
      <% else %>
        <!-- ログインしていない場合 -->
        <li><a class="glyphicon glyphicon-home" href="/"> Home</a></li>
        <li><a class="glyphicon glyphicon-link" href="/home/about"> About</a></li>
        <li><a class="glyphicon glyphicon-edit" href="/users/sign_up"> sign up</a></li>
        <li><a class="glyphicon glyphicon-log-in" href="/users/sign_in"> login</a></li>
      <% end %>
    </ul>
  </nav>
</div>
</header>
<!-- main -->
  <div class="contianer" style="margin-top: 60px;">
    <div class="text-success"><%= notice %></div>
    <div class="row">
      <%= yield %>
    </div>
  </div>
<!-- footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">CopyRight Infratop.inc</div>
        </div>
      </div>
    </footer>
  </body>
</html>